server:
   port: 0

management:
   endpoints:
        web:
         exposure:
            include: '*'

---
spring:
   profiles: admin-client
   boot:
      admin:
         client:
            url: http://localhost:9090

---

spring:
   profiles: eureka-client
eureka:
   enabled: true
   client:
     serviceUrl:
        defaultZone: http://localhost:8761/eureka/

---

spring:
   profiles: zipkin-client
   zipkin:
       baseUrl: http://127.0.0.1:9411/
